### ISSUE TITLE
monit sidekiq 設定

### ISSUE THREAD

**Issue by marsz** [5fpro/saturn#1]

**Comment by marsz** [comment]
@phrase5036 ahah

**Comment by marsz** [comment]
@phrase5036 haha

**Comment by phrase5036** [comment]
@marsz PR : https://github.com/5fpro/saturn/pull/2

哥先merge測過一輪
哥天元突破了, https://github.com/5fpro/saturn/pull/2/commits/7e3112832de6c5a7b1d47c2f20a9fbd1e6127818

不管你執行幾次她都不會一直塞, 如果他要塞就會在exit上面塞

**Comment by marsz** [comment]
@phrase5036  強強哥 !

**Comment by marsz** [comment]
@phrase5036 https://github.com/5fpro/saturn/commit/b79a3eab5b82564bbc668c34edb7fd6fe7f62fa6

這一個 commit review 完就可以關了
目前只有 thewall 那邊的機器還是跑舊版的
等 gem update 後會再換回新版，我會在那邊開一張票找時間解決

**Comment by marsz** [comment]
你看完這張就可以 close 了

**Comment by phrase5036** [comment]
已讀
