### ISSUE TITLE
Nginx 安裝與設定

### ISSUE THREAD

**Issue by marsz** [5fpro/saturn#6]
1. 偵測與安裝
2. 最佳化預設設定檔
3. 設定獨立網站
4. 獨立網站設定最佳化

**Comment by marsz** [comment]
PR: https://github.com/5fpro/saturn/pull/5

**Comment by marsz** [comment]
@phrase5036 https://github.com/5fpro/saturn/pull/5 看完可關

**Comment by phrase5036** [comment]
@marsz 已看, 感謝
