### ISSUE TITLE
所有專案改用 ssh-agent

### ISSUE THREAD

**Issue by marsz** [5fpro/saturn#8]
user 也都統一搬到 apps 下

**Comment by marsz** [comment]
mars
- thweall, musico
- musou
- jupiter

**Comment by phrase5036** [comment]
phrase
- jrf
- nude, nudetw
- user 都設定到apps下, 其他user砍掉

**Comment by marsz** [comment]
@phrase5036 slackistrano 這個 gem 新版的很難用，不好自定訊息內容，所以我先固定在 3.0.1 這個版本，所有專案都會弄，再提醒你這邊也要注意

**Comment by marsz** [comment]
note: 搬 user 的時候，原本用土星建立的 /etc/init.d/unicorn-xxxx (還有 sidekiq-xxx) 裡面的 user 和 group 也要一起換 c.c. @phrase5036

**Comment by marsz** [comment]
note2: /tmp/unicorn.jupiter.sock 這種的也要刪掉，才能用 apps 這個 user 去啟動

**Comment by marsz** [comment]
Note 3: PR 給你參考 https://github.com/5fpro/jupiter/pull/149

**Comment by marsz** [comment]
補 note 2-1: 然後 process 也要先手動 kill 掉，因為 sidekiq 和 unicorn process 會是原本舊 user 的 (jupiter) ，但 deploy 會用新 user (apps) 執行，導致權限不同，所以要先做完以上這三件事情:
1. 修改 /etc/init.d/{unicorn|sidekiq}-xxx 裡面的 user & group
2. kill process
3. rm /tmp/unicorn.xxx.sock
才能執行 deploy

然後 PR 看仔細一點

**Comment by marsz** [comment]
@phrase5036 嘔心瀝血 5 小時 + debug 終於搞定
上面都有 note
另外有幾件事情我都會順便做，也跟你說一下:
1. capistrano 都更新到 3.6.1
2. slackistrano 都更新到 3.0.1
3. server 上面的 ruby version 假如是 2.2.x 或 2.1.x 的，順便更新到 2.3.1 ，然後改 .ruby-version 。並且在 capistrano 裡面強制設定 rvm 的版本直接讀 .ruby-version 這個檔案。但 jupiter 我沒有改，因為機器剛好在跟你那邊要弄的專案同一台，所以就交給你弄了

**Comment by phrase5036** [comment]
PRs: 
- nudetw : https://github.com/5fpro/nudetw/pull/56
- nude: https://github.com/5fpro/nude/pull/391
- jrf: https://github.com/5fpro/jrf-sunny/pull/599
- jupiter : https://github.com/5fpro/jupiter/pull/152

我把不要的/home/xxx砍掉了, 所有設定都在apps底下, 包含logrotate

**Comment by marsz** [comment]
@phrase5036 這張我可以 close 了對吧?

**Comment by marsz** [comment]
@phrase5036 觀?

**Comment by phrase5036** [comment]
@marsz yessss, finished

**Comment by marsz** [comment]
@phrase5036 deploy key 都從 github 刪除了嗎?

**Comment by phrase5036** [comment]
@marsz 上述project的設定全部都只剩下codeship在使用的那把而已
