### ISSUE TITLE
所有專案幹掉 therubyrace 改用 nodejs

### ISSUE THREAD

**Issue by marsz** [5fpro/saturn#9]
mars
- thewall, musico, musou

phrase
- jrf, jupiter
- nudeshop, nudetw

**Comment by marsz** [comment]
還要 mac 安裝 nodejs 的 sop

**Comment by marsz** [comment]
PRs:
- https://github.com/5fpro/thewall/pull/501
- musico: https://github.com/5fpro/musico/pull/43
- musou: 之前已經做好了，所以這裡不再列舉
  這兩個 PR 裡面都有修 spec 的 code ，可忽略，看第一個 commit 就好

**Comment by phrase5036** [comment]
PRs
- nude : https://github.com/5fpro/nude/pull/390
- nudetw : https://github.com/5fpro/nudetw/pull/57
- jrf : https://github.com/5fpro/jrf-sunny/pull/601
- jupiter : https://github.com/5fpro/jupiter/pull/153

**Comment by marsz** [comment]
@phrase5036 這張票我也可以關了?

**Comment by phrase5036** [comment]
可以哦, 我先關惹

**Comment by marsz** [comment]
@phrase5036 test fuck

**Comment by phrase5036** [comment]
@marsz got it

**Comment by marsz** [comment]
@phrase5036 這張票也是可以關?

**Comment by phrase5036** [comment]
對的 全部做完並且部署沒問題了 (已關了)
